In [1]:
import numpy as np

In [2]:
arrayoriginal=np.array([[1,2,3],[4,5,6],[7,8,9]])
arrayoriginal

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arrayview=arrayoriginal[1:,1:]
arrayview

array([[5, 6],
       [8, 9]])

In [5]:
arrayview[0,0]=99
arrayview

array([[99,  6],
       [ 8,  9]])

In [6]:
arrayoriginal

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [7]:
arraycopia= arrayoriginal.copy()
arraycopia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [9]:
arraycopia[0,0]=100
arrayoriginal

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])