In [1]:
import numpy as np

In [3]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [4]:
posicao = np.where(array ==30)
posicao

(array([2]),)

In [5]:
notas = np.array    ([55,67,72,48,90,85,60,50])
notas

array([55, 67, 72, 48, 90, 85, 60, 50])

In [6]:
alunosaprovados=np.where(notas >60)
alunosaprovados

(array([1, 2, 4, 5]),)

In [7]:
notas[alunosaprovados]

array([67, 72, 90, 85])

In [8]:
notamaximo=np.max(notas)
notamaximo

np.int64(90)

In [9]:
indicemax=np.argmax(notas)
indicemax

np.int64(4)