In [5]:
import numpy as np

In [6]:
array1d=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
array2d = array1d.reshape(3,4)
array2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
pixel =np.arange(64)
pixel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [9]:
imagem = pixel.reshape(8,8)
imagem

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [10]:
imageminvertida=63-imagem
imageminvertida

array([[63, 62, 61, 60, 59, 58, 57, 56],
       [55, 54, 53, 52, 51, 50, 49, 48],
       [47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32],
       [31, 30, 29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1,  0]])