In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6])

In [3]:
arraydivid= np.split(array,3)
arraydivid

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for i, value in enumerate  (arraydivid):
    print(f"parte {i+1}->{value}")

parte 1->[1 2]
parte 2->[3 4]
parte 3->[5 6]


In [5]:
temperaturas = np.array([22,21,23,25,20,19,21,24,26,27,25,22,20,18,19,20,21,22,23,24,25,26,27,28,29,30,29,28,27,26,25,24])
temperaturas

array([22, 21, 23, 25, 20, 19, 21, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [6]:
semanas = np.split(temperaturas,4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [7]:
for i , value in enumerate (semanas):
    print(f"Semana {i+1}: {value}")

Semana 1: [22 21 23 25 20 19 21 24]
Semana 2: [26 27 25 22 20 18 19 20]
Semana 3: [21 22 23 24 25 26 27 28]
Semana 4: [29 30 29 28 27 26 25 24]


In [8]:
media_semana = [np.mean(semana) for semana in semanas]
media_semana

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [9]:
for i, value in enumerate (media_semana):
    print(f"Media da semana {i+1}: {value:.2f}ºC")

Media da semana 1: 21.88ºC
Media da semana 2: 22.12ºC
Media da semana 3: 24.50ºC
Media da semana 4: 27.25ºC
